const {test}=require('node:test');const assert=require('node:assert/strict');
const {initial,apply,totals}=require('../../seed-model.js');
function earned(){let s=initial();for(const [r,a,p] of [['user','request',{title:'包装の手伝い',consent:true}],['operator','publish'],['user','join'],['operator','match',{confirmed:true}],['user','complete'],['operator','award',{confirmed:true}]])s=apply(s,r,a,p);return s;}
test('full cycle and accounting conservation',()=>{let s=earned();assert.equal(s.balance,500);s=apply(s,'user','pay',{amount:300});assert.equal(s.balance,500);s=apply(s,'merchant','accept');assert.equal(s.balance,200);assert.equal(totals(s).unsettled,300);s=apply(s,'operator','settle',{confirmed:true});assert.deepEqual(totals(s),{issued:500,used:300,unsettled:0,settled:300});assert.equal(totals(s).issued,s.balance+totals(s).used);});
test('consent and valid request required',()=>{for(const p of [{title:'x'},{title:'',consent:true},{title:'x'.repeat(81),consent:true}])assert.throws(()=>apply(initial(),'user','request',p));});
test('role and sequence gates',()=>{assert.throws(()=>apply(initial(),'operator','request',{title:'x',consent:true}));assert.throws(()=>apply(initial(),'user','complete'));assert.throws(()=>apply(earned(),'user','award',{confirmed:true}));});
test('duplicate award, receipt and settlement rejected',()=>{let s=earned();assert.throws(()=>apply(s,'operator','award',{confirmed:true}));s=apply(s,'user','pay',{amount:300});assert.throws(()=>apply(s,'user','pay',{amount:100}));s=apply(s,'merchant','accept');assert.throws(()=>apply(s,'merchant','accept'));s=apply(s,'operator','settle',{confirmed:true});assert.throws(()=>apply(s,'operator','settle',{confirmed:true}));});
test('invalid amount and overdraft rejected',()=>{for(const amount of [0,-1,501,1.5,NaN,Infinity])assert.throws(()=>apply(earned(),'user','pay',{amount}));});
test('cancel preserves balance; immutable input',()=>{const s=earned();const pending=apply(s,'user','pay',{amount:300});assert.equal(s.pending,null);const cancelled=apply(pending,'user','cancel');assert.equal(cancelled.balance,500);assert.equal(cancelled.pending,null);assert.equal(pending.pending.amount,300);});
test('human confirmation required for match, award and settlement',()=>{let s=initial();s=apply(s,'user','request',{title:'x',consent:true});s=apply(s,'operator','publish');s=apply(s,'user','join');assert.throws(()=>apply(s,'operator','match'));s=apply(s,'operator','match',{confirmed:true});s=apply(s,'user','complete');assert.throws(()=>apply(s,'operator','award'));s=apply(s,'operator','award',{confirmed:true});s=apply(s,'user','pay',{amount:100});s=apply(s,'merchant','accept');assert.throws(()=>apply(s,'operator','settle'));});
